### ISSUE TITLE
Failed to load command `sk` 

### ISSUE THREAD

**Issue by keyfer** [SchoolKeep/schoolkeep-templates#5]
When trying to run `bundle exec sk server`:

![https://screenshot.click/13-44-r8w70-ew5z9.jpg](https://screenshot.click/13-44-r8w70-ew5z9.jpg)

I did all the `bundle` installs

**Comment by philbenoit-ibsa** [comment]
I have exactly the same issue.

**Comment by damshaw** [comment]
Is this repo still good for use or is it archived? 

I cannot get this working due to what appears to be missing gems.. any ideas?

`Could not find gem 'schoolkeep' in git://github.com/SchoolKeep/schoolkeep-ruby.git (at master@4ccc26f).
The source does not contain any versions of 'schoolkeep'`

**Comment by tomasz-krol** [comment]
@damshaw Sorry for the delay. Unfortunately, we no longer support setting up a development environment for the purpose of testing custom templates.
